let Phone=119.95;
console.log("Price of one phone is:");
console.log(Phone+"$");
console.log("The amount of phones bought is: 30");
let LotsOfPhones=Phone*30;
console.log("Price for that many phones is:");
console.log(LotsOfPhones+"$");
console.log("After a tax rate of 5% the price is:");
let tax=LotsOfPhones*0.05;
console.log(tax+LotsOfPhones+"$");
